### ISSUE TITLE
Inav blackbox graph problem

### ISSUE THREAD

**Issue by the-ptr** [iNavFlight/blackbox-tools#17]
Hi,
My Inav BlackBox logs look strange, there are no graphs but boxes.
I already reflashed the Matek F722SE with Inav 2.5.1 but the issue stays.
Can you help me fix this issue? 

Google drive link to one of my logs:
https://drive.google.com/file/d/1Xm7KhXEFCu-ZXsyHw_plfClZgWB8W8uF/view?usp=sharing

Screenshot: 
![image](https://user-images.githubusercontent.com/15247277/89131019-37285200-d50a-11ea-80c6-56353b306e22.png)

**Comment by stronnag** [comment]
Wrong project, belongs in https://github.com/iNavFlight/blackbox-log-viewer
