### ISSUE TITLE
blackbox_decode creates spaces in header CSV

### ISSUE THREAD

**Issue by OMGChase** [iNavFlight/blackbox-tools#40]
Hi there.

I've noticed that in the headers of the exported CSV file using the blackbox_decode have a space before the heading name.
For example, "axisRate[0]" will actually be " axisRate[0]"

**Comment by stronnag** [comment]
It's always been like that for some reason.
Maybe I'll see if removing the spaces upsets extant consumers, and it not maybe I'll change it.

**Comment by stronnag** [comment]
Maybe you can test out #41 and see if it meets your expections?

**Comment by OMGChase** [comment]
> Maybe you can test out #41 and see if it meets your expections?

Seems correct to me. Thanks! Will mark as closed, thanks for the quick fix.
