### ISSUE TITLE
feature request: add debug variables to blackbox_decode

### ISSUE THREAD

**Issue by bw1129** [iNavFlight/blackbox-tools#45]
Hi. Currently blackbox decode for inav does not export debug variables as far as I can tell. It'd be great to add this. 
cheers! -Brian (PIDtoolbox) https://github.com/bw1129/PIDtoolbox

**Comment by bw1129** [comment]
I think you’re referring to debugging the program. I’m talking about the variable that contains prefiltered gyro data or any other blackbox log debug data you want to look at. It’s not being parsed out into the extracted csv file.

**Comment by stronnag** [comment]
I have a number of 3rd party logs here with `debug_mode` != 0. In each case, 'debug[n]` columns exist in the log. 

I've just created (a bench test) log with `H debug_mode:1` (aka `GYRO`). The log contains the `debug[n]` columns 
What am I missing here?

**Comment by bw1129** [comment]
ah geez, I see what I did now. my bad. So sorry bout the confusion. thx guys
