### ISSUE TITLE
INAV 7 not logging yaw set point or rc command

### ISSUE THREAD

**Issue by bw1129** [iNavFlight/blackbox-tools#72]
I notice that yaw set point and yaw RC command are not being logging in INAV 7. Tried logfiles from serveral different sources. It just shows a string of zeros. roll and pitch are fine. here is a screenshot of an example, zoomed 500%. yaw (YELLOW) is perfectly flat with no deviation from 0. 

![image](https://github.com/iNavFlight/blackbox-tools/assets/17284912/fc873f66-d2e3-41bc-ad69-69c2b6c4e9cc)

**Comment by stronnag** [comment]
Wrong project.
