### ISSUE TITLE
Feature request: select mode for stick overlay

### ISSUE THREAD

**Issue by RobertoD91** [iNavFlight/blackbox-tools#79]
It would be useful to have the option to select a different mode, apart from Mode 2, for the on-screen overlay of the sticks. In Italy, Mode 1 is widely used for model aircraft.

**Comment by stronnag** [comment]
@RobertoD91 
There is a PR https://github.com/iNavFlight/blackbox-tools/pull/80 that adds `--mode MODE` option and should draw the sticks according to requested mode (the default mode remains mode 2 for backwards compatibility).

Can you please test this in mode 1. 
Let me know the preferred OS / Architecture if you'd like me to build a binary for you.

**Comment by RobertoD91** [comment]
Thank you for the fast implementation! After a quick test (build commit 0fdadf2b4a5f4104f451bd5627a9c047127f9fbb on intel macos 14.4.1) seems perfect!

**Comment by stronnag** [comment]
Addressed in #80
