### ISSUE TITLE
Increase FLIGHT_LOG_MAX_SERVOS to 18?

### ISSUE THREAD

**Issue by bartslinger** [iNavFlight/blackbox-tools#87]
MAX_SUPPORTED_SERVOS in INAV was increased to 18 in this commit https://github.com/iNavFlight/inav/commit/b6f29761270b261290d549bcf02a64ff43d33d61

That breaks the parser, because it assumes 16:
https://github.com/iNavFlight/blackbox-tools/blob/6eb2fe722c93120688eaff5acd3c00956b73b028/src/parser.h#L20

Trivial solution would be to increase FLIGHT_LOG_MAX_SERVOS to 18, but than it can no longer parse old logs. So I'm not sure what would be the best approach here.

**Comment by stronnag** [comment]
@bartslinger 

Thanks. I'll fix it, we have much ugliness already and a means to cope.

**Comment by stronnag** [comment]
Actually it doesn't break old logs, the `FLIGHT_LOG_MAX_SERVOS` macro means "up to". So the trivial fix is the fix.

Committed to the (now misnamed) `inav8_rcmodes` branch.

Thanks for finding this.

**Comment by bartslinger** [comment]
`MAX_SERVOS` also need to be increased:

https://github.com/iNavFlight/blackbox-tools/blob/a957e6e8da27379a094a5214f939254575f4166c/src/blackbox_render.c#L43

Or perhaps there should only be one definition?

**Comment by stronnag** [comment]
Done, uses `parser.h` valus

**Comment by mmosca** [comment]
Does this mean that file based blackbox on  sitl works now?
