### ISSUE TITLE
build on MacOS Sonoma  arm64 fails with missing symbols

### ISSUE THREAD

**Issue by silicongarage** [iNavFlight/blackbox-tools#92]
<img width="762" alt="image" src="https://github.com/user-attachments/assets/67146b52-2a9b-47de-a418-bb71f0036707">

[make.log](https://github.com/user-attachments/files/17836019/make.log)

**Comment by stronnag** [comment]
Not surprising. The shared libaries are ia32 (which somehow work on x86_64, at least when compiled natively, if not cross-compiled from Linux).

I will (a) update the draft release note and (b) fix the Makefile by removing the legacy DLLs, so the user will have to supply their own via `homebrew`.
